# Generated by Django 5.2.5 on 2025-08-17 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('creat_update', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=400)),
                ('adress', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True, help_text='for checking activaty of brach')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('creat_update', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('creat_update', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=400)),
                ('national_code', models.CharField(max_length=1, unique=True)),
                ('gender', models.CharField(choices=[('0', 'Female'), ('1', 'Male'), ('2', 'Other')], default='2', max_length=15)),
                ('birthday', models.DateField()),
                ('adress', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('creat_update', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=400)),
                ('national_code', models.CharField(max_length=1, unique=True)),
                ('birthday', models.DateField()),
                ('adress', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('gender', models.CharField(choices=[('0', 'Female'), ('1', 'Male'), ('2', 'Other')], default='2', max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('creat_update', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('buy_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('date_price', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
            ],
            options={
                'verbose_name_plural': 'Price',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('creat_update', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('type_pic', models.CharField(choices=[('0', 'Picture'), ('1', 'Icon'), ('2', 'Document'), ('3', 'Other')], default='0', max_length=15)),
                ('image', models.ImageField(upload_to='products/')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.customer')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.staff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('creat_update', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('type_deal', models.CharField(choices=[('0', 'Sell'), ('1', 'Buy')], default='0', max_length=15)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.price')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.staff')),
            ],
            options={
                'verbose_name_plural': 'Price',
            },
        ),
        migrations.CreateModel(
            name='StaffBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('creat_update', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('possion', models.CharField(choices=[('0', 'Boss'), ('1', 'Seller'), ('2', 'Accountant'), ('3', 'Cleaner')], default='1', max_length=15)),
                ('startdate', models.DateField()),
                ('solary', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff')),
            ],
            options={
                'verbose_name_plural': 'StaffBranches',
                'unique_together': {('branch', 'possion'), ('staff', 'branch', 'possion')},
            },
        ),
    ]
